// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package com_island_code_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MakeTokenRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeTokenRequest) Reset()         { *m = MakeTokenRequest{} }
func (m *MakeTokenRequest) String() string { return proto.CompactTextString(m) }
func (*MakeTokenRequest) ProtoMessage()    {}
func (*MakeTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *MakeTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeTokenRequest.Unmarshal(m, b)
}
func (m *MakeTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeTokenRequest.Marshal(b, m, deterministic)
}
func (m *MakeTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeTokenRequest.Merge(m, src)
}
func (m *MakeTokenRequest) XXX_Size() int {
	return xxx_messageInfo_MakeTokenRequest.Size(m)
}
func (m *MakeTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeTokenRequest proto.InternalMessageInfo

func (m *MakeTokenRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MakeTokenRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type MakeTokenResponse struct {
	Error                *Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *MakeTokenData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MakeTokenResponse) Reset()         { *m = MakeTokenResponse{} }
func (m *MakeTokenResponse) String() string { return proto.CompactTextString(m) }
func (*MakeTokenResponse) ProtoMessage()    {}
func (*MakeTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *MakeTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeTokenResponse.Unmarshal(m, b)
}
func (m *MakeTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeTokenResponse.Marshal(b, m, deterministic)
}
func (m *MakeTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeTokenResponse.Merge(m, src)
}
func (m *MakeTokenResponse) XXX_Size() int {
	return xxx_messageInfo_MakeTokenResponse.Size(m)
}
func (m *MakeTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeTokenResponse proto.InternalMessageInfo

func (m *MakeTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *MakeTokenResponse) GetData() *MakeTokenData {
	if m != nil {
		return m.Data
	}
	return nil
}

type MakeTokenData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeTokenData) Reset()         { *m = MakeTokenData{} }
func (m *MakeTokenData) String() string { return proto.CompactTextString(m) }
func (*MakeTokenData) ProtoMessage()    {}
func (*MakeTokenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *MakeTokenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeTokenData.Unmarshal(m, b)
}
func (m *MakeTokenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeTokenData.Marshal(b, m, deterministic)
}
func (m *MakeTokenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeTokenData.Merge(m, src)
}
func (m *MakeTokenData) XXX_Size() int {
	return xxx_messageInfo_MakeTokenData.Size(m)
}
func (m *MakeTokenData) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeTokenData.DiscardUnknown(m)
}

var xxx_messageInfo_MakeTokenData proto.InternalMessageInfo

func (m *MakeTokenData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DelTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTokenRequest) Reset()         { *m = DelTokenRequest{} }
func (m *DelTokenRequest) String() string { return proto.CompactTextString(m) }
func (*DelTokenRequest) ProtoMessage()    {}
func (*DelTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{3}
}

func (m *DelTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTokenRequest.Unmarshal(m, b)
}
func (m *DelTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTokenRequest.Marshal(b, m, deterministic)
}
func (m *DelTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTokenRequest.Merge(m, src)
}
func (m *DelTokenRequest) XXX_Size() int {
	return xxx_messageInfo_DelTokenRequest.Size(m)
}
func (m *DelTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelTokenRequest proto.InternalMessageInfo

func (m *DelTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DelTokenResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTokenResponse) Reset()         { *m = DelTokenResponse{} }
func (m *DelTokenResponse) String() string { return proto.CompactTextString(m) }
func (*DelTokenResponse) ProtoMessage()    {}
func (*DelTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{4}
}

func (m *DelTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTokenResponse.Unmarshal(m, b)
}
func (m *DelTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTokenResponse.Marshal(b, m, deterministic)
}
func (m *DelTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTokenResponse.Merge(m, src)
}
func (m *DelTokenResponse) XXX_Size() int {
	return xxx_messageInfo_DelTokenResponse.Size(m)
}
func (m *DelTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelTokenResponse proto.InternalMessageInfo

func (m *DelTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetCachedTokenRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCachedTokenRequest) Reset()         { *m = GetCachedTokenRequest{} }
func (m *GetCachedTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetCachedTokenRequest) ProtoMessage()    {}
func (*GetCachedTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{5}
}

func (m *GetCachedTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCachedTokenRequest.Unmarshal(m, b)
}
func (m *GetCachedTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCachedTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetCachedTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCachedTokenRequest.Merge(m, src)
}
func (m *GetCachedTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetCachedTokenRequest.Size(m)
}
func (m *GetCachedTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCachedTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCachedTokenRequest proto.InternalMessageInfo

func (m *GetCachedTokenRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetCachedTokenRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type GetCachedTokenResponse struct {
	Error                *Error              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *GetCachedTokenData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetCachedTokenResponse) Reset()         { *m = GetCachedTokenResponse{} }
func (m *GetCachedTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetCachedTokenResponse) ProtoMessage()    {}
func (*GetCachedTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{6}
}

func (m *GetCachedTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCachedTokenResponse.Unmarshal(m, b)
}
func (m *GetCachedTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCachedTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetCachedTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCachedTokenResponse.Merge(m, src)
}
func (m *GetCachedTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetCachedTokenResponse.Size(m)
}
func (m *GetCachedTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCachedTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCachedTokenResponse proto.InternalMessageInfo

func (m *GetCachedTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetCachedTokenResponse) GetData() *GetCachedTokenData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetCachedTokenData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCachedTokenData) Reset()         { *m = GetCachedTokenData{} }
func (m *GetCachedTokenData) String() string { return proto.CompactTextString(m) }
func (*GetCachedTokenData) ProtoMessage()    {}
func (*GetCachedTokenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{7}
}

func (m *GetCachedTokenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCachedTokenData.Unmarshal(m, b)
}
func (m *GetCachedTokenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCachedTokenData.Marshal(b, m, deterministic)
}
func (m *GetCachedTokenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCachedTokenData.Merge(m, src)
}
func (m *GetCachedTokenData) XXX_Size() int {
	return xxx_messageInfo_GetCachedTokenData.Size(m)
}
func (m *GetCachedTokenData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCachedTokenData.DiscardUnknown(m)
}

var xxx_messageInfo_GetCachedTokenData proto.InternalMessageInfo

func (m *GetCachedTokenData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginByNameData struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	LoginPwd             string   `protobuf:"bytes,3,opt,name=loginPwd,proto3" json:"loginPwd,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	DeviceID             string   `protobuf:"bytes,5,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginByNameData) Reset()         { *m = LoginByNameData{} }
func (m *LoginByNameData) String() string { return proto.CompactTextString(m) }
func (*LoginByNameData) ProtoMessage()    {}
func (*LoginByNameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{8}
}

func (m *LoginByNameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginByNameData.Unmarshal(m, b)
}
func (m *LoginByNameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginByNameData.Marshal(b, m, deterministic)
}
func (m *LoginByNameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginByNameData.Merge(m, src)
}
func (m *LoginByNameData) XXX_Size() int {
	return xxx_messageInfo_LoginByNameData.Size(m)
}
func (m *LoginByNameData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginByNameData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginByNameData proto.InternalMessageInfo

func (m *LoginByNameData) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *LoginByNameData) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *LoginByNameData) GetLoginPwd() string {
	if m != nil {
		return m.LoginPwd
	}
	return ""
}

func (m *LoginByNameData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginByNameData) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type LoginByNameRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	LoginPwd             string   `protobuf:"bytes,2,opt,name=loginPwd,proto3" json:"loginPwd,omitempty"`
	DeviceID             string   `protobuf:"bytes,3,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginByNameRequest) Reset()         { *m = LoginByNameRequest{} }
func (m *LoginByNameRequest) String() string { return proto.CompactTextString(m) }
func (*LoginByNameRequest) ProtoMessage()    {}
func (*LoginByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{9}
}

func (m *LoginByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginByNameRequest.Unmarshal(m, b)
}
func (m *LoginByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginByNameRequest.Marshal(b, m, deterministic)
}
func (m *LoginByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginByNameRequest.Merge(m, src)
}
func (m *LoginByNameRequest) XXX_Size() int {
	return xxx_messageInfo_LoginByNameRequest.Size(m)
}
func (m *LoginByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginByNameRequest proto.InternalMessageInfo

func (m *LoginByNameRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *LoginByNameRequest) GetLoginPwd() string {
	if m != nil {
		return m.LoginPwd
	}
	return ""
}

func (m *LoginByNameRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type LoginByNameResponse struct {
	Error                *Error           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *LoginByNameData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoginByNameResponse) Reset()         { *m = LoginByNameResponse{} }
func (m *LoginByNameResponse) String() string { return proto.CompactTextString(m) }
func (*LoginByNameResponse) ProtoMessage()    {}
func (*LoginByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{10}
}

func (m *LoginByNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginByNameResponse.Unmarshal(m, b)
}
func (m *LoginByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginByNameResponse.Marshal(b, m, deterministic)
}
func (m *LoginByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginByNameResponse.Merge(m, src)
}
func (m *LoginByNameResponse) XXX_Size() int {
	return xxx_messageInfo_LoginByNameResponse.Size(m)
}
func (m *LoginByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginByNameResponse proto.InternalMessageInfo

func (m *LoginByNameResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LoginByNameResponse) GetData() *LoginByNameData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdatePasswordRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{11}
}

func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(m, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdatePasswordResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResponse) Reset()         { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()    {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{12}
}

func (m *UpdatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResponse.Merge(m, src)
}
func (m *UpdatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResponse.Size(m)
}
func (m *UpdatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResponse proto.InternalMessageInfo

func (m *UpdatePasswordResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LogoutEvent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SentTime             int64    `protobuf:"varint,2,opt,name=sentTime,proto3" json:"sentTime,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutEvent) Reset()         { *m = LogoutEvent{} }
func (m *LogoutEvent) String() string { return proto.CompactTextString(m) }
func (*LogoutEvent) ProtoMessage()    {}
func (*LogoutEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{13}
}

func (m *LogoutEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutEvent.Unmarshal(m, b)
}
func (m *LogoutEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutEvent.Marshal(b, m, deterministic)
}
func (m *LogoutEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutEvent.Merge(m, src)
}
func (m *LogoutEvent) XXX_Size() int {
	return xxx_messageInfo_LogoutEvent.Size(m)
}
func (m *LogoutEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutEvent proto.InternalMessageInfo

func (m *LogoutEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LogoutEvent) GetSentTime() int64 {
	if m != nil {
		return m.SentTime
	}
	return 0
}

func (m *LogoutEvent) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{14}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*MakeTokenRequest)(nil), "com.island.code.srv.auth.MakeTokenRequest")
	proto.RegisterType((*MakeTokenResponse)(nil), "com.island.code.srv.auth.MakeTokenResponse")
	proto.RegisterType((*MakeTokenData)(nil), "com.island.code.srv.auth.MakeTokenData")
	proto.RegisterType((*DelTokenRequest)(nil), "com.island.code.srv.auth.DelTokenRequest")
	proto.RegisterType((*DelTokenResponse)(nil), "com.island.code.srv.auth.DelTokenResponse")
	proto.RegisterType((*GetCachedTokenRequest)(nil), "com.island.code.srv.auth.GetCachedTokenRequest")
	proto.RegisterType((*GetCachedTokenResponse)(nil), "com.island.code.srv.auth.GetCachedTokenResponse")
	proto.RegisterType((*GetCachedTokenData)(nil), "com.island.code.srv.auth.GetCachedTokenData")
	proto.RegisterType((*LoginByNameData)(nil), "com.island.code.srv.auth.LoginByNameData")
	proto.RegisterType((*LoginByNameRequest)(nil), "com.island.code.srv.auth.LoginByNameRequest")
	proto.RegisterType((*LoginByNameResponse)(nil), "com.island.code.srv.auth.LoginByNameResponse")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "com.island.code.srv.auth.UpdatePasswordRequest")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "com.island.code.srv.auth.UpdatePasswordResponse")
	proto.RegisterType((*LogoutEvent)(nil), "com.island.code.srv.auth.LogoutEvent")
	proto.RegisterType((*Error)(nil), "com.island.code.srv.auth.Error")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xd1, 0x6e, 0xd3, 0x4a,
	0x10, 0xad, 0x63, 0xbb, 0xba, 0x9d, 0xe8, 0x36, 0x61, 0x69, 0xa2, 0x28, 0x42, 0x02, 0x59, 0x42,
	0x85, 0xd0, 0xba, 0x28, 0x88, 0x27, 0x84, 0x44, 0xc1, 0x05, 0x45, 0x2d, 0x50, 0xac, 0xf6, 0x03,
	0x16, 0x7b, 0x94, 0x98, 0x3a, 0xde, 0xe0, 0x5d, 0xa7, 0x42, 0x7c, 0x00, 0x0f, 0x3c, 0xf1, 0xc0,
	0x27, 0xf1, 0x5f, 0xc8, 0x1b, 0xdb, 0xb1, 0x4d, 0x1c, 0x59, 0xf2, 0x4b, 0xe4, 0x63, 0x9f, 0x99,
	0x33, 0x73, 0x66, 0x76, 0x03, 0xbd, 0x45, 0xc8, 0x04, 0x3b, 0xa1, 0x91, 0x98, 0xc9, 0x1f, 0x53,
	0x62, 0x32, 0x70, 0xd8, 0xdc, 0xf4, 0xb8, 0x4f, 0x03, 0xd7, 0x74, 0x98, 0x8b, 0x26, 0x0f, 0x97,
	0x66, 0xfc, 0xdd, 0x78, 0x0b, 0xdd, 0xf7, 0xf4, 0x06, 0xaf, 0xd8, 0x0d, 0x06, 0x36, 0x7e, 0x8d,
	0x90, 0x0b, 0xd2, 0x87, 0xdd, 0x88, 0x63, 0x38, 0xb1, 0x06, 0xca, 0x03, 0xe5, 0xd1, 0x9e, 0x9d,
	0x20, 0x32, 0x84, 0xff, 0x5c, 0x5c, 0x7a, 0x0e, 0x4e, 0xac, 0x41, 0x4b, 0x7e, 0xc9, 0xb0, 0xf1,
	0x43, 0x81, 0x3b, 0xb9, 0x44, 0x7c, 0xc1, 0x02, 0x8e, 0xe4, 0x39, 0xe8, 0x18, 0x86, 0x2c, 0x94,
	0x89, 0xda, 0xe3, 0xfb, 0x66, 0x55, 0x1d, 0xe6, 0x59, 0x4c, 0xb3, 0x57, 0x6c, 0xf2, 0x02, 0x34,
	0x97, 0x0a, 0x2a, 0x45, 0xda, 0xe3, 0xc3, 0xea, 0xa8, 0x4c, 0xd1, 0xa2, 0x82, 0xda, 0x32, 0xc8,
	0x78, 0x08, 0xff, 0x17, 0x5e, 0x93, 0x03, 0xd0, 0x45, 0x0c, 0x92, 0x6e, 0x56, 0xc0, 0x38, 0x84,
	0x8e, 0x85, 0x7e, 0xa1, 0xef, 0xcd, 0xc4, 0x09, 0x74, 0xd7, 0xc4, 0x46, 0x7d, 0x19, 0xe7, 0xd0,
	0x7b, 0x87, 0xe2, 0x0d, 0x75, 0x66, 0xe8, 0x36, 0x76, 0xfc, 0x97, 0x02, 0xfd, 0x72, 0xb6, 0x66,
	0xb6, 0xbf, 0x2a, 0xd8, 0x7e, 0x54, 0x1d, 0x55, 0x94, 0xcd, 0x79, 0x3f, 0x02, 0xf2, 0xef, 0xb7,
	0x0a, 0x5f, 0x7f, 0x2b, 0xd0, 0xb9, 0x60, 0x53, 0x2f, 0x78, 0xfd, 0xed, 0x03, 0x9d, 0xa3, 0x64,
	0x56, 0xf9, 0x70, 0x0f, 0xf6, 0xfc, 0x98, 0x1a, 0x13, 0x13, 0x23, 0xd6, 0x2f, 0x62, 0x97, 0x24,
	0xb8, 0xbc, 0x75, 0x07, 0xea, 0xca, 0xa5, 0x14, 0xaf, 0xb5, 0xb5, 0x9c, 0x76, 0xc1, 0x57, 0xbd,
	0xe4, 0xeb, 0x17, 0x20, 0xb9, 0xb2, 0xd2, 0x09, 0x15, 0x2a, 0x50, 0xb6, 0x55, 0xd0, 0x2a, 0x55,
	0x90, 0xd7, 0x52, 0x4b, 0x5a, 0x3f, 0x15, 0xb8, 0x5b, 0x10, 0x6b, 0x36, 0xc0, 0x97, 0x85, 0x01,
	0x3e, 0xae, 0x8e, 0x2a, 0xf9, 0x9e, 0x4c, 0xef, 0x1c, 0x7a, 0xd7, 0x0b, 0x97, 0x0a, 0xbc, 0xa4,
	0x9c, 0xdf, 0xb2, 0xd0, 0xad, 0xb1, 0x9e, 0x8b, 0x84, 0x9a, 0xb6, 0x9d, 0x62, 0xe3, 0x23, 0xf4,
	0xcb, 0xc9, 0x9a, 0x1d, 0x9e, 0x4f, 0xd0, 0xbe, 0x60, 0x53, 0x16, 0x89, 0xb3, 0x25, 0x06, 0x82,
	0xec, 0x43, 0xcb, 0x73, 0x93, 0x7a, 0x5a, 0x9e, 0xb4, 0x99, 0x63, 0x20, 0xae, 0xbc, 0x64, 0x43,
	0x54, 0x3b, 0xc3, 0xb9, 0xfa, 0xd5, 0x7c, 0xfd, 0xc6, 0x31, 0xe8, 0x52, 0x82, 0x10, 0xd0, 0x62,
	0x65, 0x99, 0x4e, 0xb7, 0xe5, 0x33, 0xe9, 0x82, 0x3a, 0xe7, 0xd3, 0xa4, 0xaf, 0xf8, 0x71, 0xfc,
	0x47, 0x03, 0xed, 0x34, 0x12, 0x33, 0xe2, 0x43, 0x27, 0xbe, 0x62, 0x4e, 0x1d, 0x07, 0x39, 0x97,
	0x7b, 0x4e, 0x46, 0x35, 0x2e, 0xa9, 0xc4, 0xce, 0xe1, 0x93, 0x5a, 0xdc, 0x95, 0x5b, 0xc6, 0x0e,
	0x99, 0x03, 0xb1, 0xd0, 0xbf, 0xe6, 0x18, 0xe6, 0x05, 0xb7, 0x4c, 0xb7, 0x74, 0xaf, 0x0d, 0x47,
	0x75, 0xa8, 0x99, 0xdc, 0x77, 0x38, 0xc8, 0xce, 0x70, 0x5e, 0xf0, 0xa4, 0xee, 0x7d, 0x90, 0xca,
	0x3e, 0xad, 0x1f, 0x90, 0x89, 0xfb, 0x72, 0xc8, 0xe9, 0x6e, 0x92, 0xa3, 0x5a, 0x2b, 0x9c, 0x0a,
	0x1e, 0xd7, 0x64, 0x67, 0x6a, 0x11, 0xec, 0x17, 0x77, 0x74, 0x5b, 0x93, 0x1b, 0x8f, 0xc6, 0xb6,
	0x26, 0x37, 0xaf, 0xbf, 0xb1, 0xf3, 0x79, 0x57, 0xfe, 0x29, 0x3f, 0xfb, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x03, 0x17, 0xa5, 0x50, 0xad, 0x07, 0x00, 0x00,
}
