// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package com_island_code_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MakeTokenRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeTokenRequest) Reset()         { *m = MakeTokenRequest{} }
func (m *MakeTokenRequest) String() string { return proto.CompactTextString(m) }
func (*MakeTokenRequest) ProtoMessage()    {}
func (*MakeTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *MakeTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeTokenRequest.Unmarshal(m, b)
}
func (m *MakeTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeTokenRequest.Marshal(b, m, deterministic)
}
func (m *MakeTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeTokenRequest.Merge(m, src)
}
func (m *MakeTokenRequest) XXX_Size() int {
	return xxx_messageInfo_MakeTokenRequest.Size(m)
}
func (m *MakeTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeTokenRequest proto.InternalMessageInfo

func (m *MakeTokenRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MakeTokenRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type MakeTokenResponse struct {
	Error                *Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *MakeTokenData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MakeTokenResponse) Reset()         { *m = MakeTokenResponse{} }
func (m *MakeTokenResponse) String() string { return proto.CompactTextString(m) }
func (*MakeTokenResponse) ProtoMessage()    {}
func (*MakeTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *MakeTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeTokenResponse.Unmarshal(m, b)
}
func (m *MakeTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeTokenResponse.Marshal(b, m, deterministic)
}
func (m *MakeTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeTokenResponse.Merge(m, src)
}
func (m *MakeTokenResponse) XXX_Size() int {
	return xxx_messageInfo_MakeTokenResponse.Size(m)
}
func (m *MakeTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeTokenResponse proto.InternalMessageInfo

func (m *MakeTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *MakeTokenResponse) GetData() *MakeTokenData {
	if m != nil {
		return m.Data
	}
	return nil
}

type MakeTokenData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeTokenData) Reset()         { *m = MakeTokenData{} }
func (m *MakeTokenData) String() string { return proto.CompactTextString(m) }
func (*MakeTokenData) ProtoMessage()    {}
func (*MakeTokenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *MakeTokenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeTokenData.Unmarshal(m, b)
}
func (m *MakeTokenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeTokenData.Marshal(b, m, deterministic)
}
func (m *MakeTokenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeTokenData.Merge(m, src)
}
func (m *MakeTokenData) XXX_Size() int {
	return xxx_messageInfo_MakeTokenData.Size(m)
}
func (m *MakeTokenData) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeTokenData.DiscardUnknown(m)
}

var xxx_messageInfo_MakeTokenData proto.InternalMessageInfo

func (m *MakeTokenData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DelTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTokenRequest) Reset()         { *m = DelTokenRequest{} }
func (m *DelTokenRequest) String() string { return proto.CompactTextString(m) }
func (*DelTokenRequest) ProtoMessage()    {}
func (*DelTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{3}
}

func (m *DelTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTokenRequest.Unmarshal(m, b)
}
func (m *DelTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTokenRequest.Marshal(b, m, deterministic)
}
func (m *DelTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTokenRequest.Merge(m, src)
}
func (m *DelTokenRequest) XXX_Size() int {
	return xxx_messageInfo_DelTokenRequest.Size(m)
}
func (m *DelTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelTokenRequest proto.InternalMessageInfo

func (m *DelTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DelTokenResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTokenResponse) Reset()         { *m = DelTokenResponse{} }
func (m *DelTokenResponse) String() string { return proto.CompactTextString(m) }
func (*DelTokenResponse) ProtoMessage()    {}
func (*DelTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{4}
}

func (m *DelTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTokenResponse.Unmarshal(m, b)
}
func (m *DelTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTokenResponse.Marshal(b, m, deterministic)
}
func (m *DelTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTokenResponse.Merge(m, src)
}
func (m *DelTokenResponse) XXX_Size() int {
	return xxx_messageInfo_DelTokenResponse.Size(m)
}
func (m *DelTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelTokenResponse proto.InternalMessageInfo

func (m *DelTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetCachedTokenRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCachedTokenRequest) Reset()         { *m = GetCachedTokenRequest{} }
func (m *GetCachedTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetCachedTokenRequest) ProtoMessage()    {}
func (*GetCachedTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{5}
}

func (m *GetCachedTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCachedTokenRequest.Unmarshal(m, b)
}
func (m *GetCachedTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCachedTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetCachedTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCachedTokenRequest.Merge(m, src)
}
func (m *GetCachedTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetCachedTokenRequest.Size(m)
}
func (m *GetCachedTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCachedTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCachedTokenRequest proto.InternalMessageInfo

func (m *GetCachedTokenRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetCachedTokenRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type GetCachedTokenResponse struct {
	Error                *Error              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *GetCachedTokenData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetCachedTokenResponse) Reset()         { *m = GetCachedTokenResponse{} }
func (m *GetCachedTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetCachedTokenResponse) ProtoMessage()    {}
func (*GetCachedTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{6}
}

func (m *GetCachedTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCachedTokenResponse.Unmarshal(m, b)
}
func (m *GetCachedTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCachedTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetCachedTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCachedTokenResponse.Merge(m, src)
}
func (m *GetCachedTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetCachedTokenResponse.Size(m)
}
func (m *GetCachedTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCachedTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCachedTokenResponse proto.InternalMessageInfo

func (m *GetCachedTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetCachedTokenResponse) GetData() *GetCachedTokenData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetCachedTokenData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCachedTokenData) Reset()         { *m = GetCachedTokenData{} }
func (m *GetCachedTokenData) String() string { return proto.CompactTextString(m) }
func (*GetCachedTokenData) ProtoMessage()    {}
func (*GetCachedTokenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{7}
}

func (m *GetCachedTokenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCachedTokenData.Unmarshal(m, b)
}
func (m *GetCachedTokenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCachedTokenData.Marshal(b, m, deterministic)
}
func (m *GetCachedTokenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCachedTokenData.Merge(m, src)
}
func (m *GetCachedTokenData) XXX_Size() int {
	return xxx_messageInfo_GetCachedTokenData.Size(m)
}
func (m *GetCachedTokenData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCachedTokenData.DiscardUnknown(m)
}

var xxx_messageInfo_GetCachedTokenData proto.InternalMessageInfo

func (m *GetCachedTokenData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type QueryUserData struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	LoginPwd             string   `protobuf:"bytes,3,opt,name=loginPwd,proto3" json:"loginPwd,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	DeviceID             string   `protobuf:"bytes,5,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserData) Reset()         { *m = QueryUserData{} }
func (m *QueryUserData) String() string { return proto.CompactTextString(m) }
func (*QueryUserData) ProtoMessage()    {}
func (*QueryUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{8}
}

func (m *QueryUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserData.Unmarshal(m, b)
}
func (m *QueryUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserData.Marshal(b, m, deterministic)
}
func (m *QueryUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserData.Merge(m, src)
}
func (m *QueryUserData) XXX_Size() int {
	return xxx_messageInfo_QueryUserData.Size(m)
}
func (m *QueryUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserData.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserData proto.InternalMessageInfo

func (m *QueryUserData) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *QueryUserData) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *QueryUserData) GetLoginPwd() string {
	if m != nil {
		return m.LoginPwd
	}
	return ""
}

func (m *QueryUserData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *QueryUserData) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type QueryUserRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserRequest) Reset()         { *m = QueryUserRequest{} }
func (m *QueryUserRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserRequest) ProtoMessage()    {}
func (*QueryUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{9}
}

func (m *QueryUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserRequest.Unmarshal(m, b)
}
func (m *QueryUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserRequest.Marshal(b, m, deterministic)
}
func (m *QueryUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserRequest.Merge(m, src)
}
func (m *QueryUserRequest) XXX_Size() int {
	return xxx_messageInfo_QueryUserRequest.Size(m)
}
func (m *QueryUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserRequest proto.InternalMessageInfo

func (m *QueryUserRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

type QueryUserResponse struct {
	Error                *Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *QueryUserData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryUserResponse) Reset()         { *m = QueryUserResponse{} }
func (m *QueryUserResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserResponse) ProtoMessage()    {}
func (*QueryUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{10}
}

func (m *QueryUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserResponse.Unmarshal(m, b)
}
func (m *QueryUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserResponse.Marshal(b, m, deterministic)
}
func (m *QueryUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserResponse.Merge(m, src)
}
func (m *QueryUserResponse) XXX_Size() int {
	return xxx_messageInfo_QueryUserResponse.Size(m)
}
func (m *QueryUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserResponse proto.InternalMessageInfo

func (m *QueryUserResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *QueryUserResponse) GetData() *QueryUserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{11}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*MakeTokenRequest)(nil), "com.island.code.srv.auth.MakeTokenRequest")
	proto.RegisterType((*MakeTokenResponse)(nil), "com.island.code.srv.auth.MakeTokenResponse")
	proto.RegisterType((*MakeTokenData)(nil), "com.island.code.srv.auth.MakeTokenData")
	proto.RegisterType((*DelTokenRequest)(nil), "com.island.code.srv.auth.DelTokenRequest")
	proto.RegisterType((*DelTokenResponse)(nil), "com.island.code.srv.auth.DelTokenResponse")
	proto.RegisterType((*GetCachedTokenRequest)(nil), "com.island.code.srv.auth.GetCachedTokenRequest")
	proto.RegisterType((*GetCachedTokenResponse)(nil), "com.island.code.srv.auth.GetCachedTokenResponse")
	proto.RegisterType((*GetCachedTokenData)(nil), "com.island.code.srv.auth.GetCachedTokenData")
	proto.RegisterType((*QueryUserData)(nil), "com.island.code.srv.auth.QueryUserData")
	proto.RegisterType((*QueryUserRequest)(nil), "com.island.code.srv.auth.QueryUserRequest")
	proto.RegisterType((*QueryUserResponse)(nil), "com.island.code.srv.auth.QueryUserResponse")
	proto.RegisterType((*Error)(nil), "com.island.code.srv.auth.Error")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xe1, 0x8a, 0xd3, 0x40,
	0x10, 0xc7, 0x2f, 0x36, 0x39, 0xbc, 0x39, 0x8e, 0xc6, 0xe5, 0xee, 0x08, 0x45, 0x50, 0x02, 0x72,
	0x1a, 0x35, 0x77, 0x54, 0xfc, 0xe4, 0x17, 0x4f, 0xa3, 0x52, 0x44, 0xd1, 0xa0, 0x0f, 0xb0, 0x26,
	0x43, 0x5b, 0x9a, 0x64, 0xeb, 0xee, 0xa6, 0x52, 0x7c, 0x00, 0x3f, 0x8b, 0xef, 0xe5, 0x33, 0xc9,
	0x6e, 0xd2, 0x34, 0x49, 0x0d, 0x04, 0x0a, 0xf7, 0xa5, 0x64, 0x76, 0xff, 0x33, 0xff, 0xdd, 0xdf,
	0xcc, 0x16, 0xce, 0x96, 0x9c, 0x49, 0x76, 0x49, 0x73, 0x39, 0xd3, 0x3f, 0xbe, 0x8e, 0x89, 0x13,
	0xb1, 0xd4, 0x9f, 0x8b, 0x84, 0x66, 0xb1, 0x1f, 0xb1, 0x18, 0x7d, 0xc1, 0x57, 0xbe, 0xda, 0x77,
	0xdf, 0x82, 0xfd, 0x81, 0x2e, 0xf0, 0x0b, 0x5b, 0x60, 0x16, 0xe2, 0xf7, 0x1c, 0x85, 0x24, 0xe7,
	0x70, 0x98, 0x0b, 0xe4, 0x93, 0xc0, 0x31, 0xee, 0x1b, 0x0f, 0x8f, 0xc2, 0x32, 0x22, 0x23, 0xb8,
	0x1d, 0xe3, 0x6a, 0x1e, 0xe1, 0x24, 0x70, 0x6e, 0xe9, 0x9d, 0x2a, 0x76, 0x7f, 0x19, 0x70, 0xa7,
	0x56, 0x48, 0x2c, 0x59, 0x26, 0x90, 0x3c, 0x07, 0x0b, 0x39, 0x67, 0x5c, 0x17, 0x3a, 0x1e, 0xdf,
	0xf3, 0xbb, 0xce, 0xe1, 0xbf, 0x51, 0xb2, 0xb0, 0x50, 0x93, 0x17, 0x60, 0xc6, 0x54, 0x52, 0x6d,
	0x72, 0x3c, 0xbe, 0xe8, 0xce, 0xaa, 0x1c, 0x03, 0x2a, 0x69, 0xa8, 0x93, 0xdc, 0x07, 0x70, 0xd2,
	0x58, 0x26, 0xa7, 0x60, 0x49, 0x15, 0x94, 0xb7, 0x29, 0x02, 0xf7, 0x02, 0x86, 0x01, 0x26, 0x8d,
	0x7b, 0xff, 0x5f, 0x38, 0x01, 0x7b, 0x2b, 0xdc, 0xeb, 0x5e, 0xee, 0x7b, 0x38, 0x7b, 0x87, 0xf2,
	0x35, 0x8d, 0x66, 0x18, 0xef, 0x4d, 0xfc, 0xb7, 0x01, 0xe7, 0xed, 0x6a, 0xfb, 0x61, 0x7f, 0xd9,
	0xc0, 0xfe, 0xa4, 0x3b, 0xab, 0x69, 0x5b, 0x63, 0xef, 0x01, 0xd9, 0xdd, 0xeb, 0xe0, 0xfa, 0xc7,
	0x80, 0x93, 0xcf, 0x39, 0xf2, 0xf5, 0x57, 0x81, 0x5c, 0xeb, 0xba, 0x28, 0xdc, 0x85, 0xa3, 0x84,
	0x4d, 0xe7, 0xd9, 0x47, 0x9a, 0x62, 0x89, 0x61, 0xbb, 0xa0, 0x18, 0xe9, 0xe0, 0xd3, 0x8f, 0xd8,
	0x19, 0x14, 0x8c, 0x36, 0xf1, 0xd6, 0xd9, 0xac, 0x39, 0x37, 0xa8, 0x5a, 0x2d, 0xaa, 0x57, 0x60,
	0x57, 0x87, 0xda, 0x74, 0xa7, 0xe1, 0x6f, 0xb4, 0xfc, 0xf5, 0xe4, 0xd7, 0x52, 0x6e, 0x68, 0xf2,
	0x1b, 0xe4, 0x4a, 0xfa, 0x4f, 0xc1, 0xd2, 0xc5, 0x08, 0x01, 0x53, 0xa9, 0xb5, 0xb7, 0x15, 0xea,
	0x6f, 0x62, 0xc3, 0x20, 0x15, 0xd3, 0x12, 0x9f, 0xfa, 0x1c, 0xff, 0x1d, 0x80, 0x79, 0x9d, 0xcb,
	0x19, 0x49, 0x60, 0xa8, 0x5e, 0xcc, 0x75, 0x14, 0xa1, 0x10, 0xba, 0x6d, 0xc4, 0xeb, 0xf1, 0xe6,
	0x4a, 0x3c, 0xa3, 0xc7, 0xbd, 0xb4, 0x05, 0x17, 0xf7, 0x80, 0xa4, 0x40, 0x02, 0x4c, 0xd4, 0xd1,
	0xeb, 0x86, 0x8f, 0xba, 0x8b, 0xb4, 0x9e, 0xe9, 0xc8, 0xeb, 0x23, 0xad, 0xec, 0x7e, 0xc2, 0x69,
	0x35, 0x92, 0x75, 0xc3, 0xcb, 0xbe, 0xe3, 0xbd, 0xb1, 0xbd, 0xea, 0x9f, 0x50, 0x99, 0x27, 0x30,
	0xac, 0x1a, 0xf5, 0x6a, 0xad, 0xc7, 0xd5, 0xeb, 0xd1, 0xd3, 0x1e, 0x64, 0x77, 0x26, 0xce, 0x3d,
	0xf8, 0x76, 0xa8, 0xff, 0xec, 0x9f, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xa7, 0x9e, 0x4b,
	0x05, 0x06, 0x00, 0x00,
}
